# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7e78054b0d3a86d0e3ca864ae83ff8d2"
name = "b2b-app"
handle = "b2b-app-15"
application_url = "https://realtors-angel-bold-unto.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "shery-store-3.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_assigned_fulfillment_orders,read_cart_transforms,read_customer_events,read_customers,read_discounts,read_draft_orders,read_files,read_fulfillments,read_gift_cards,read_inventory,read_locations,read_metaobject_definitions,read_metaobjects,read_order_edits,read_price_rules,read_product_feeds,read_product_listings,read_products,read_publications,read_purchase_options,read_shipping,write_assigned_fulfillment_orders,write_cart_transforms,write_customers,write_discounts,write_draft_orders,write_files,write_fulfillments,write_gift_cards,write_inventory,write_locations,write_metaobject_definitions,write_metaobjects,write_order_edits,write_price_rules,write_product_feeds,write_product_listings,write_products,write_publications,write_purchase_options,write_shipping"

[auth]
redirect_urls = [
  "https://realtors-angel-bold-unto.trycloudflare.com/auth/callback",
  "https://realtors-angel-bold-unto.trycloudflare.com/auth/shopify/callback",
  "https://realtors-angel-bold-unto.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
