/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/v12jGL79UuV
 */
import { CardContent, CardTitle, CardHeader, Card } from "@/components/ui/card"

export function ProductCard() {
  return (
    <Card className="w-full max-w-xs mx-auto flex-col items-start">
      <CardContent className="p-0">
        <img
          alt="Product Image"
          className="aspect-square object-cover rounded-t-lg min-w-0 w-full"
          height={300}
          src="/placeholder.svg"
          width={300}
        />
      </CardContent>
      <CardHeader className="text-center">
        <CardTitle className="text-base font-bold">Acme Circles T-Shirt</CardTitle>
      </CardHeader>
    </Card>
  )
}
